### ISSUE TITLE
你好 作者

### ISSUE THREAD

**Issue by yanglilizhang** [shenbengit/TTSTool#1]
你好 作者 这个项目可以在商用项目使用吗 讯飞收费的吗

**Comment by shenbengit** [comment]
不建议商用，我现在用的sdk是以前的，新版的sdk免费版有有效期，以前的版本貌似没有，至少目前使用还是正常的，但仅支持普通的男女声。条件允许建议使用收费版。

**Comment by yanglilizhang** [comment]
好的谢谢。我用的是更老的sdk,是没有有效期问题的，但是由于so的限制所以想换下，我先试试你这个

**Comment by yanglilizhang** [comment]
> 不建议商用，我现在用的sdk是以前的，新版的sdk免费版有有效期，以前的版本貌似没有，至少目前使用还是正常的，但仅支持普通的男女声。条件允许建议使用收费版。

好的 谢谢
